### PR TITLE
Update go.mod

### PR DESCRIPTION
**Pull request by amolonf**
Update go.mod file to go 1.19

### CODE REVIEW

**Review by SeanCondon — COMMENTED** [review]
@amolonf you will have to change `go.sum` at the same time as `go.mod` - run `go mod tidy` in the folder and it will be updated

I tried this out myself - the next problem you will have is that `golang-ci-lint` will not work with go 1.19

To update this you will have to change ../build-tools common Makefile

Then once that's sorted, you will have to fix linting errors that the new version detects.

I think someone familiar with the code should help out with this CC @adibrastegarnia and @tomikazi

**Comment by amolonf** [comment]
> @amolonf you will have to change `go.sum` at the same time as `go.mod` - run `go mod tidy` in the folder and it will be updated
> 
> I tried this out myself - the next problem you will have is that `golang-ci-lint` will not work with go 1.19
> 
> To update this you will have to change ../build-tools common Makefile
> 
> Then once that's sorted, you will have to fix linting errors that the new version detects.
> 
> I think someone familiar with the code should help out with this CC @adibrastegarnia and @tomikazi

Thank you. @SeanCondon

**Comment by SeanCondon** [comment]
@amolonf I have created https://github.com/onosproject/build-tools/pull/208 to get the `golanci-lint` issue sorted

**Comment by SeanCondon** [comment]
retest this please

**Comment by SeanCondon** [comment]
@amolonf can you add
```
    - "package-comments: should have a package comment"
```
to the end of `.golangci.yml` please, and see how far this gets

**Comment by SeanCondon** [comment]
also I can see it is still picking up 1.42 of golangci-lint

**Comment by amolonf** [comment]
> @amolonf I have created [onosproject/build-tools#208](https://github.com/onosproject/build-tools/pull/208) to get the `golanci-lint` issue sorted

Thank you @SeanCondon

**Comment by SeanCondon** [comment]
@amolonf looking at the Jenkins log for this I can see 
```
21:16:50 golangci-lint --version || curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b `go env GOPATH`/bin v1.50.0
21:16:50 golangci-lint has version 1.42.0 built from c6142e38 on 2021-08-17T11:47:22Z
21:16:50 golangci-lint run --timeout 15m
```

what this is saying to me is:
1. it is trying to see if a version of `golangci-lint` is installed in the build container
2. if it's not then download and install version 1.50.0 of it

It's clear from the 2nd line that because it has reported a version, that it already has the wrong version installed, and is not going to install the correct one.

The rest of the build fails because of this

Can you change the build container, so that it has v1.50.0 in it please.

**Comment by SeanCondon** [comment]
retest this please

**Comment by amolonf** [comment]
retest this please

**Comment by amolonf** [comment]
retest this please

**Comment by amolonf** [comment]
> retest this please

Now, lint version 1.42 has been updated to 1.50

**Comment by adibrastegarnia** [comment]
> @amolonf can you add
> 
> ```
>     - "package-comments: should have a package comment"
> ```
> 
> to the end of `.golangci.yml` please, and see how far this gets

@amolonf  Please add this and some of the linter issues will be gone. I guess one will be left and easy to fix.  io/utils should be replaced by io in one of the packages.

**Comment by SeanCondon** [comment]
retest this please

**Review by SeanCondon — APPROVED** [review]
we have liftoff. Thanks to @adibrastegarnia for the other patch

**Pull request merged**
